// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    AUTH_SECRET: string;
    MAIN_SERVER_URL: string;
    SERVER_URL: string;
    SERVERS: string;
    CLIENT_ID: string;
    SELF_URL: string;
    ASSETS: Fetcher;
}
