// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_SECRET: string;
	SERVER_URL: string;
	CLIENT_ID: string;
	SELF_URL: string;
	ASSETS: Fetcher;
}
