/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NofooterAuthSignInIndexRouteImport } from './routes/_nofooter/auth/sign-in/index'
import { Route as NofooterTermsIndexRouteImport } from './routes/_nofooter/terms/index'
import { Route as Signed_inSplatRouteImport } from './routes/_signed_in/$'
import { Route as Signed_inIndexRouteImport } from './routes/_signed_in/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const Signed_inIndexRoute = Signed_inIndexRouteImport.update({
  id: '/_signed_in/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Signed_inSplatRoute = Signed_inSplatRouteImport.update({
  id: '/_signed_in/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NofooterTermsIndexRoute = NofooterTermsIndexRouteImport.update({
  id: '/_nofooter/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NofooterAuthSignInIndexRoute = NofooterAuthSignInIndexRouteImport.update({
  id: '/_nofooter/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof Signed_inSplatRoute
  '/': typeof Signed_inIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/terms': typeof NofooterTermsIndexRoute
  '/auth/sign-in': typeof NofooterAuthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof Signed_inSplatRoute
  '/': typeof Signed_inIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/terms': typeof NofooterTermsIndexRoute
  '/auth/sign-in': typeof NofooterAuthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_signed_in/$': typeof Signed_inSplatRoute
  '/_signed_in/': typeof Signed_inIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_nofooter/terms/': typeof NofooterTermsIndexRoute
  '/_nofooter/auth/sign-in/': typeof NofooterAuthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/' | '/api/auth/$' | '/terms' | '/auth/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/api/auth/$' | '/terms' | '/auth/sign-in'
  id:
    | '__root__'
    | '/_signed_in/$'
    | '/_signed_in/'
    | '/api/auth/$'
    | '/_nofooter/terms/'
    | '/_nofooter/auth/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Signed_inSplatRoute: typeof Signed_inSplatRoute
  Signed_inIndexRoute: typeof Signed_inIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  NofooterTermsIndexRoute: typeof NofooterTermsIndexRoute
  NofooterAuthSignInIndexRoute: typeof NofooterAuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_signed_in/': {
      id: '/_signed_in/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Signed_inIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_signed_in/$': {
      id: '/_signed_in/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof Signed_inSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nofooter/terms/': {
      id: '/_nofooter/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof NofooterTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_nofooter/auth/sign-in/': {
      id: '/_nofooter/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof NofooterAuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Signed_inSplatRoute: Signed_inSplatRoute,
  Signed_inIndexRoute: Signed_inIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  NofooterTermsIndexRoute: NofooterTermsIndexRoute,
  NofooterAuthSignInIndexRoute: NofooterAuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { createStart } from '@tanstack/react-start'
import type { getRouter } from './router.ts'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
